### PR TITLE
Update ContentHelper.cs

### PR DESCRIPTION
**Pull request by SonicZeHedgehog**
Adjusted index for new Dawntrail dungeons.

### CODE REVIEW

**Comment by SonicZeHedgehog** [comment]
Oh, see there's another pull request about this.

**Comment by SonicZeHedgehog** [comment]
Wait, just noticed they didn't account for the earlier dungeons. Keeping this up. Pull whichever you want.

**Comment by adambennett55** [comment]
I am not in dawntrail yet and cannot test this myself, is this still needed after DallagenXYZ's pull request is merged? does it need 200 or 192?

**Comment by DallagenXYZ** [comment]
> I am not in dawntrail yet and cannot test this myself, is this still needed after DallagenXYZ's pull request is merged? does it need 200 or 192?

both commits achieve the same result, the three lines I added in duty support manager to match how you handle shb and endwalker by loading the tabs and checking how many dungeons are in the list to form an offset do the same thing

**Comment by SonicZeHedgehog** [comment]
I haven't looked too deeply in their code, but modifying to 32 and 192 should be all your need.

**Pull request closed without merging**
