### PR TITLE
Added Jump and PausePandora command

### PR DESCRIPTION
**Pull request by erdelf**
Jump command with a bit of pre-running
PausePandora to pause pandora's box features like Auto-Interact

Existing paths in the repository adjusted as an example.

### CODE REVIEW

**Comment by VeraNala** [comment]
Do you think Pandora still sees any use after the recent interactable changes? Personally I've been wondering if its even really needed anymore.

**Comment by erdelf** [comment]
I don't see what the object id targeting would change in regards to pandora usage. It doesn't change much for the english users, and that is the majority of who we are dealing with daily.

**Comment by Redmoonwow** [comment]
I play with the JP client, but I can't use the interact action without using Pandora, so I think it's necessary at least until AutoDuty supports multiple languages.

**Comment by erdelf** [comment]
It already does ? We have already changed multiple paths to use object ids instead of localized names

**Comment by Redmoonwow** [comment]
I tried using it without Pandora, but the interact action didn't work. Could you let me know if there was any mistake in my attempt?

**Comment by erdelf** [comment]
I don't know which path you tried so.. best come around the discord and we can talk directly.

**Comment by Redmoonwow** [comment]
I will. If you are interested in the information that the JP client still uses pandora to replace interact actions, please let me know.

**Comment by VeraNala** [comment]
Likely will need to replace paths or figure out why people are not getting the updated paths on repo updates.
I went through all duty support paths with fuuga and added the interactable objects using the new objID method.

And to my earlier question, it's not that we are using OBJ ID or not it's a question of if it's still needed after you and Herc modified the interaction step itself to be more reliable (no longer needing separate movement and interaction steps, etc.)

**Comment by erdelf** [comment]
talked with Redmoon on discord and their problem is solved btw.

Either way, we probably want to pause pandora during these things then anyway if we feel like it must be us who do the interact.

**Comment by fuuga-2915** [comment]
I didn't originally use Pandora's auto-interact feature.
If Path was perfect, we wouldn't need Pandora's auto-interact.
(Unless the ObjID I checked is wrong or I forgot to include the interact in the path)

**Comment by VeraNala** [comment]
I don't think you missed any, ty again for your help fuuga!
Sidenote for Erdelf though -> Obj ID auto fetches objects, but I couldn't get it to fetch NPCs.
Fuuga got the ID for it but Brayflox has the goblin you need to interact with and I'm not sure how they got the ID or whether or not the step actually works w/ npcs (I didn't get a chance to test, sorry!)

**Pull request merged**
