### PR TITLE
adding some duty paths i've been sitting on for a bit

### PR DESCRIPTION
**Pull request by pot0to**

### CODE REVIEW

**Comment by erdelf** [comment]
uh.. several of those dungeons already have paths. What do yours do differently ?

**Comment by pot0to** [comment]
Oh... I thought since these files weren't in the repo that meant they weren't in AutoDuty. Let me check again which of these files are actually new. What's the proper place to check the list of dungeons with paths, if they're not all checked in here and my `%AppData%/XIVLauncher/pluginConfigs/AutoDuty/paths` directory might be dirty?

**Comment by erdelf** [comment]
They are in the repo. [Halatali](https://github.com/ffxivcode/AutoDuty/blob/master/AutoDuty/Paths/(1245)%20Halatali.json) and [Fractal Continuum](https://github.com/ffxivcode/AutoDuty/blob/master/AutoDuty/Paths/(743)%20the%20Fractal%20Continuum%20(Hard).json) for example..

**Comment by pot0to** [comment]
Alright, I think I've cleaned up the PR, sorry about that. I believe the remaining ones should be new -- at least they all show up as new files in the diff and a manual search of master via browser doesn't bring them up.

**Comment by erdelf** [comment]
looks good, thank you.

**Pull request merged**
